name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Check formatting
        run: npm run check-format
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Run eslint
        run: npm run lint
